version: '3.8'

services:
  web:
    build: . # Xây dựng từ Dockerfile trong thư mục hiện tại
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db       # <--- THAY ĐỔI QUAN TRỌNG: Sử dụng tên service 'db'
      DB_USER: root
      DB_PASSWORD: ''   # Mật khẩu này phải khớp với MYSQL_ROOT_PASSWORD
      DB_NAME: foodnow

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '' # Để trống nếu bạn muốn root không có mật khẩu
      MYSQL_DATABASE: foodnow # MySQL sẽ tự tạo database này nếu chưa có
    volumes:
      # Mount thư mục chứa init.sql vào vị trí mà MySQL sẽ tự động chạy
      - ./mysql-initdb:/docker-entrypoint-initdb.d
      # Volume để lưu trữ dữ liệu MySQL, giúp dữ liệu không bị mất khi container dừng/xóa
      - db_data:/var/lib/mysql
    # ports: # Bỏ comment nếu bạn muốn truy cập MySQL từ máy host (ví dụ: bằng HeidiSQL, DBeaver)
      # - "3306:3306"

volumes:
  db_data:
    # Driver mặc định là 'local', không cần khai báo gì thêm