name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Kích hoạt workflow khi có push lên nhánh 'main'
  pull_request:
    branches:
      - master # Chạy workflow khi có pull request đến nhánh 'main'

env:
  # Thay thế 'lequochuy2004' bằng TÊN ĐĂNG NHẬP Docker Hub của bạn
  DOCKER_IMAGE_NAME: lequochuy2004/foodnow

jobs:
  test:
    name: Run PHP Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, dom, pdo, pdo_mysql # Thêm các extension PHP cần thiết cho project của bạn
          tools: composer # Cài đặt Composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }} # Thêm github.run_id để key luôn mới
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true' # Chỉ chạy nếu không có cache
        run: composer install --prefer-dist --no-progress --no-suggest

      # ---- THÊM CÁC BƯỚC TEST CỤ THỂ CỦA BẠN VÀO ĐÂY ----
      # Ví dụ: Chạy PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        # Hoặc nếu bạn có script trong composer.json:
        # run: composer test

      # Ví dụ: Chạy PHP Lint (kiểm tra cú pháp)
      - name: Run PHP Lint
        run: find . -name '*.php' -not -path "./vendor/*" -exec php -l {} \;
        # Hoặc nếu bạn có script trong composer.json:
        # run: composer lint

  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test # Job này chỉ chạy SAU KHI job 'test' hoàn thành thành công

    # Chỉ build và push image khi push lên nhánh master, không phải khi tạo PR
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
